ecommerce:
    #resource: "@EcommerceBundle/Controller/"
    #type: annotation
    path: /
    defaults: { _controller: EcommerceBundle:Default:index }

app:
    resource: '@AppBundle/Controller/'
    type: annotation




